language: ruby

bundler_args: --deployment --without development

rvm:
- 1.9.3-p448

script: bundle exec rspec spec

before_script:
- mysql -u root -e "DELETE FROM mysql.user WHERE Host='localhost' AND User=''"
- mysql -u root -e "SHOW VARIABLES"
