development:
  database:
    admin_user: root
    admin_password: password
    host: localhost
    port: 3306
    singleton_database: development

test:
  database:
    admin_user: root
    admin_password:
    host: localhost
    port: 3306
    singleton_database: test