development:
  database:
    admin_user: root
    admin_password: password
    host: localhost
    port: 3306

test:
  database:
    admin_user: root
    admin_password: password
    host: localhost
    port: 3306